---
- name: Setup
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Commandline Tools
      community.general.pacman:
        name:
          - bluez-utils
          - cifs-utils
          - cups
          - dosfstools
          - fwupd
          - fzf
          - gdu
          - inetutils
          - jq
          - man-db
          - networkmanager
          - qmk
          - reflector
          - ripgrep
          - sshfs
          - udiskie
          - unrar
          - unzip
          - wget
          - zip
        state: present
      become: true

    - name: Commandline Tools AUR
      kewlfft.aur.aur:
        name:
          - downgrade
          - simple-mtpfs
        use: yay
        state: present

    - name: Commandline Developer Tools
      community.general.pacman:
        name:
          - dotnet-sdk
          - git
          - git-lfs
          - neovim
          - npm
          - pnpm
        state: present
      become: true

    - name: Terminal
      community.general.pacman:
        name:
          - kitty
          - neofetch
          - zsh
          - zsh-syntax-highlighting
        state: present
      become: true

    - name: Terminal AUR
      kewlfft.aur.aur:
        name:
          - oh-my-posh-bin
        use: yay
        state: present

    - name: File Explorer
      community.general.pacman:
        name:
          - ffmpegthumbnailer
          - lf
          - trash-cli
        state: present
      become: true

    - name: File Explorer AUR
      kewlfft.aur.aur:
        name:
          - stl-thumb
        use: yay
        state: present

    - name: Hyprland
      community.general.pacman:
        name:
          - blueman
          - brightnessctl
          - cliphist
          - dunst
          - greetd-regreet
          - grim
          - hypridle
          - hyprland
          - hyprlock
          - hyprpaper
          - imv
          - qpwgraph
          - qt5-wayland
          - slurp
          - swappy
          - waybar
          - wlr-randr
        state: present
      become: true

    - name: Hyprland AUR
      kewlfft.aur.aur:
        name:
          - cava-git
          - dragon-drop
          - hyprpicker
          - rofi-lbonn-wayland-git
          - swayosd-git
          - python-pywalfox
          - wallust-git
          - waybar-module-pacman-updates-git
        use: yay
        state: present
    
    - name: Game Development
      community.general.pacman:
        name:
          - audacity
          - blender
          - gimp
          - inkscape
          - lmms
        state: present
      become: true

    - name: Game Development AUR
      kewlfft.aur.aur:
        name:
          - aseprite
          - godot-mono
        use: yay
        state: present

    - name: Applications
      community.general.pacman:
        name:
          - freecad
          - freerdp
          - guvcview
          - handbrake
          - libreoffice-fresh
          - obs-studio
          - remmina
          - simple-scan
          - steam
          - zathura
          - zathura-pdf-mupdf
        state: present
      become: true

    - name: Applications AUR
      kewlfft.aur.aur:
        name:
          - webcord
        use: yay
        state: present

