console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '<,red> > </><red,transparent></> '
  foreground = 'foreground'
  background = 'transparent'

[transient_prompt]
  template = '<,red> {{ .Folder }} </><red,transparent></> '
  foreground = 'foreground'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'foreground'
    background = 'red'
    type = 'session'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    foreground = 'foreground'
    powerline_symbol = ''
    background = 'green'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '󰋜'
      style = 'agnoster'

      [blocks.segments.properties.mapped_locations]
        '~/Documents' = '󰈙'
        '~/Downloads' = ' '
        '~/Pictures' = ' '

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'foreground'
    powerline_symbol = ''
    background = 'red'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}foreground{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}foreground{{ end }}', '{{ if gt .Ahead 0 }}foreground{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}blue{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    leading_diamond = ''
    template = '  '
    foreground = 'foreground'
    background = 'red'
    type = 'status'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ .FormattedMs }} '
    foreground = 'foreground'
    background = 'yellow'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000
