#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'session'
        style = 'powerline'
        foreground = 'foreground'
        background = 'red'
        template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '

    [[blocks.segments]]
        type = 'path'
        style = 'powerline'
        powerline_symbol = ''
        foreground = 'foreground'
        background = 'green'
        template = ' {{ .Path }} '

        [blocks.segments.properties]
            style = 'agnoster'
            home_icon = '󰋜'

            [blocks.segments.properties.mapped_locations]
            "~/Documents" = "󰈙"
            "~/Downloads" = " "
            "~/Pictures" = " "

    [[blocks.segments]]
        type = 'git'
        style = 'powerline'
        powerline_symbol = ''
        foreground = 'foreground'
        foreground_templates = [
            '{{ if or (.Working.Changed) (.Staging.Changed) }}foreground{{ end }}', 
            '{{ if and (gt .Ahead 0) (gt .Behind 0) }}foreground{{ end }}', 
            '{{ if gt .Ahead 0 }}foreground{{ end }}'
        ]
        background = 'red'
        background_templates = [
            '{{ if or (.Working.Changed) (.Staging.Changed) }}blue{{ end }}',
            '{{ if and (gt .Ahead 0) (gt .Behind 0) }}yellow{{ end }}', 
            '{{ if gt .Ahead 0 }}#49416D{{ end }}', 
            '{{ if gt .Behind 0 }}#7A306C{{ end }}'
        ]
        template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

        [blocks.segments.properties]
            branch_max_length = 25
            fetch_status = true
            fetch_upstream_icon = true

[[blocks]]
  type = 'rprompt'

    [[blocks.segments]]
        type = 'status'
        style = 'diamond'
        leading_diamond = ""
        foreground = 'foreground'
        background = 'red'
        template = '  '

    [[blocks.segments]]
        type = "executiontime"
        style = "diamond"
        leading_diamond = ""
        foreground = "foreground"
        background = "yellow"
        template = " {{ .FormattedMs }} "

        [blocks.segments.properties]
            threshold = 5000

[transient_prompt]
  foreground = 'foreground'
  background = 'transparent'
  template = '<,red> {{ .Folder }} </><red,transparent></> '

[secondary_prompt]
  foreground = 'foreground'
  background = 'transparent'
  template = '<,red> > </><red,transparent></> '
