hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("udiskie -s")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dunst")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("gammastep")
    hl.exec_cmd("xsettingsd")
    hl.exec_cmd("~/.config/wallust/rewall")
    hl.exec_cmd("hyprctl dispatch 'hl.dsp.focus({ workspace = 1 })'")
end)

hl.window_rule({ match = { title = "Steam", class = "steam" }, tile = true })
hl.window_rule({ match = { title = "Special Offers", class = "steam" }, center = true })
hl.window_rule({ match = { title = "Shutdown", class = "steam" }, center = true })
hl.window_rule({ match = { title = "Godot", class = "Godot" }, tile = true })
hl.window_rule({ match = { class = "Aseprite" }, tile = true })

hl.window_rule({ name = "Save Dialog", match = { title = "Save File" }, float = true, center = true, size = { "(monitor_w*0.5)", "(monitor_h*0.5)" } })

