# Execute apps at launch
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = udiskie -s
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch  
exec-once = hyprpaper
exec-once = waybar
exec-once = hypridle
exec-once = dunst
exec-once = swayosd-server
exec-once = gammastep
exec-once = xsettingsd
exec-once = ~/.config/wallust/rewall

# Window Rules
#windowrule = stayfocused, title:^()$,class:^(steam)$
#windowrule = minsize 1 1, title:^()$,class:^(steam)$
windowrule = tile on, match:title Steam, match:class steam
windowrule = center on, match:title Special Offers, match:class steam
windowrule = center on, match:title Shutdown, match:class steam
windowrule = tile on, match:title Godot, match:class Godot
windowrule = tile on, match:class Aseprite

windowrule {
    name = Save Dialog
    match:title = Save File
    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.5)
}
