# workspace = 1, monitor:DVI-D-1
workspace = 1, monitor:HDMI-A-2
workspace = 2, monitor:DP-1
workspace = 3, monitor:HDMI-A-1
# workspace = 4, monitor:DVI-D-1
workspace = 4, monitor:HDMI-A-2
workspace = 5, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
# workspace = 7, monitor:DVI-D-1
workspace = 7, monitor:HDMI-A-2
workspace = 8, monitor:DP-1
workspace = 9, monitor:HDMI-A-1
# workspace = 10, monitor:DVI-D-1
workspace = 10, monitor:HDMI-A-2

# Force Mouse on Workspace 1
exec-once = hyprctl dispatch workspace 1
